import { useTranslation } from "next-i18next";
import Head from "next/head";
import { useRouter } from "next/router";
const HomeContainer = () => {
  const { t, i18n } = useTranslation();
  const router = useRouter();
  const changeLanguage = (locale: string) => {
    router.push(locale === "en" ? "/en" : "/");
    i18n.changeLanguage(locale);
  };
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="">
        <h2 className="text-2xl font-bold text-red-500">{t("hello world")}</h2>
        <button onClick={() => changeLanguage("ja")} className="bg-slate-500">
          change to JP
        </button>
        <br />
        <button onClick={() => changeLanguage("en")} className="bg-slate-500">
          change to EN
        </button>
      </main>
    </>
  );
};
export default HomeContainer;
